name: Playwright Tests

on:
  push:
    branches:
     - main


jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-actions@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Run tests
        run: npx playwright test