name: NodeJS with Webpack and Playwright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Cancel previous redundant builds
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install required libraries for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libopus0 \
          libwebp6 \
          libwebpdemux2 \
          libenchant1c2a \
          libgudev-1.0-0 \
          libsecret-1-0 \
          libhyphen0 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          libgstgl-1.0-0 \
          libgst-plugins-good1.0-0 \
          libudev1 \
          libvpx6 \
          libevent-2.1-7 \
          libopus0 \
          libgstallocators-1.0-0 \
          libgstapp-1.0-0 \
          libgstpbutils-1.0-0 \
          libgstaudio-1.0-0 \
          libgstgl-1.0-0 \
          libgsttag-1.0-0 \
          libgstvideo-1.0-0 \
          libgstcodecparsers-1.0-0 \
          libgstfft-1.0-0 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libflite_usenglish1 \
          libflite_cmu_grapheme_lang1 \
          libflite_cmu_grapheme_lex1 \
          libflite_cmu_indic_lang1 \
          libflite_cmu_indic_lex1 \
          libflite_cmulex1 \
          libflite_cmu_time_awb1 \
          libflite_cmu_us_awb1 \
          libflite_cmu_us_kal16_1 \
          libflite_cmu_us_kal1 \
          libflite_cmu_us_rms1 \
          libflite_cmu_us_slt1 \
          libgles2-mesa \
          libx264-155

    - name: Build
      run: |
        npm install
        npm install -D webpack-cli
        npx playwright install
        npx playwright test

